# Generated by Django 5.2.5 on 2025-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aynekulu Molla', max_length=100)),
                ('bio', models.TextField()),
                ('degree', models.CharField(default="Bachelor's Degree", max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=50)),
            ],
        ),
    ]
