# Generated by Django 5.2.5 on 2025-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='demo_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_demo',
            new_name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(default='Software Engineering graduate from Adama Science and Technology University with a passion for full-stack development.'),
        ),
        migrations.AlterField(
            model_name='about',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(default='BSc in Software Engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='Aynekulu Molla Miniwab', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/placeholder.jpg', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(help_text='Percentage 0-100'),
        ),
    ]
