# Generated by Django 5.2.5 on 2025-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_category_alter_about_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='Aynekulu Molla', max_length=100),
        ),
    ]
