# Generated by Django 5.2.5 on 2025-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about_github_url_about_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='about',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='about',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='Aynekulu Molla Miniwab', max_length=100),
        ),
    ]
